#!/usr/bin/env python3
"""
Render the memory backlog into the two human-readable markdown artefacts.

    tools/render_backlog.py            # write both files
    tools/render_backlog.py --check    # fail if either file is stale

Generated files:
  docs/backlog.md          the ordered pull-request queue for humans
  specs/tasks/README.md    the SDD phase index and traceability matrix

Both are derived from `.sdd/memory.sql`. Edit the memory database with
`tools/memory.py`, then re-run this. Hand-editing the markdown will be
overwritten and `--check` will flag it.
"""
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import memory  # noqa: E402

REPO = Path(__file__).resolve().parent.parent

ITERATIONS = {
    "I0": ("Foundations", "Auth, audit and OpenAPI. Done when the hash chain verifies."),
    "I1": ("Registry", "Sample types, sources, samples. Done at aliquot."),
    "I2": ("Freezer map", "Storage hierarchy and slot operations. Done per spec §5."),
    "I3": ("Workflow", "Templates, jobs, tasks. Done at the queue."),
    "I4": ("ELN", "Notebooks, review, signature. Done at signature."),
    "I5": ("Search", "Finder, picklists, row-level security. Done with RLS."),
    "I6": ("MCP and LabKey bridge", "Publishing and agent access. Done when the UI runs through MCP semantics."),
    "I7": ("Operations", "Pipelines, benchmarks, runbook. Done at the runbook."),
}

SIZE_DAYS = {"XS": "under a day", "S": "1-2 days", "M": "3-5 days", "L": "5-10 days"}


def load():
    conn = memory.connect()
    backlog = conn.execute("SELECT * FROM backlog ORDER BY seq").fetchall()
    trace = defaultdict(list)
    for r in conn.execute(
        "SELECT req_id, artifact_ref FROM traceability "
        "WHERE artifact_kind='backlog' ORDER BY req_id"
    ):
        trace[r["artifact_ref"]].append(r["req_id"])
    reqs = {r["id"]: r for r in conn.execute("SELECT * FROM requirements")}
    conn.close()
    return backlog, trace, reqs


def criteria(row) -> list[str]:
    raw = row["acceptance"] or ""
    return [c.strip() for c in raw.split("|") if c.strip()]


def render_backlog(backlog, trace) -> str:
    out: list[str] = []
    w = out.append
    w("# Pull-request backlog")
    w("")
    w("Generated from the memory database by `tools/render_backlog.py`.")
    w("Do not edit this file by hand — change the database with `tools/memory.py`")
    w("and re-render.")
    w("")
    w("```bash")
    w('tools/memory.py list backlog --brief')
    w('tools/memory.py show PR-001')
    w('tools/memory.py set backlog PR-001 status in-progress')
    w("```")
    w("")

    done = sum(1 for r in backlog if r["status"] == "done")
    w(f"**{len(backlog)} pull requests**, {done} done, "
      f"{sum(1 for r in backlog if r['status'] == 'todo')} to do.")
    w("")
    w("Each item is sized to be reviewable in one sitting. An item is mergeable")
    w("only when every acceptance criterion is met and the tree is green.")
    w("")

    w("## Summary")
    w("")
    w("| PR | Iteration | Size | Title | Depends on | Status |")
    w("| --- | --- | --- | --- | --- | --- |")
    for r in backlog:
        w(f"| [{r['id']}](#{r['id'].lower()}) | {r['iteration']} | {r['size']} | "
          f"{r['title']} | {r['depends_on'] or '—'} | {r['status']} |")
    w("")

    by_iter = defaultdict(list)
    for r in backlog:
        by_iter[r["iteration"]].append(r)

    for it in sorted(by_iter):
        name, gate = ITERATIONS.get(it, (it, ""))
        w(f"## {it} — {name}")
        w("")
        if gate:
            w(f"*{gate}*")
            w("")
        for r in by_iter[it]:
            w(f"### {r['id']}")
            w("")
            w(f"**{r['title']}**")
            w("")
            w(f"- **Branch**: `{r['branch']}`")
            w(f"- **Size**: {r['size']} ({SIZE_DAYS.get(r['size'], '')})")
            w(f"- **Depends on**: {r['depends_on'] or 'nothing'}")
            w(f"- **Status**: {r['status']}")
            reqs = trace.get(r["id"], [])
            if reqs:
                w(f"- **Requirements**: {', '.join(reqs)}")
            w("")
            if r["summary"]:
                w(r["summary"])
                w("")
            cs = criteria(r)
            if cs:
                w("**Acceptance criteria**")
                w("")
                for c in cs:
                    w(f"- [ ] {c}")
                w("")
    return "\n".join(out) + "\n"


def render_tasks_readme(backlog, trace, reqs) -> str:
    out: list[str] = []
    w = out.append
    w("# Open Sample Manager — Technical Tasks")
    w("")
    w("Generated from the memory database by `tools/render_backlog.py`.")
    w("")
    w("Each pull request in the backlog is one task. The full acceptance criteria")
    w("are in `docs/backlog.md` and in the memory database; this page is the phase")
    w("index and the traceability matrix.")
    w("")

    by_iter = defaultdict(list)
    for r in backlog:
        by_iter[r["iteration"]].append(r)

    w("## Task Overview")
    w("")
    for it in sorted(by_iter):
        name, gate = ITERATIONS.get(it, (it, ""))
        items = by_iter[it]
        lo, hi = items[0]["id"], items[-1]["id"]
        w(f"### Phase {it}: {name} ({lo}–{hi})")
        w("")
        if gate:
            w(f"**Acceptance gate**: {gate}")
            w("")
        for r in items:
            w(f"**{r['id']} — {r['title']}**")
            w("")
            if r["summary"]:
                w(f"- {r['summary']}")
            w(f"- **Dependencies**: {r['depends_on'] or 'none'}")
            w(f"- **Complexity**: {r['size']} ({SIZE_DAYS.get(r['size'], '')})")
            rs = trace.get(r["id"], [])
            if rs:
                srcs = sorted({reqs[x]["source"] for x in rs if x in reqs})
                w(f"- **Requirements**: {', '.join(rs)}")
                w(f"- **Spec sections**: {', '.join(srcs)}")
            w(f"- **Status**: {r['status']}")
            w("")

    w("## Implementation Guidelines")
    w("")
    w("### Prerequisites")
    w("")
    w("- Read `memory.md`, then `AGENTS.md`.")
    w("- `tools/memory.py check` passes before you start and before you finish.")
    w("- Scaffolding tasks (PR-001 through PR-008) complete before any feature work.")
    w("")
    w("### Quality gates")
    w("")
    w("- [ ] Lint and type checks pass with zero errors")
    w("- [ ] All tests pass and coverage stays above the configured threshold")
    w("- [ ] Every acceptance criterion in the task is met, including the denials")
    w("- [ ] No secret, credential or token appears anywhere in the diff")
    w("- [ ] Every new claim about LabKey behaviour is recorded as a verification")
    w("- [ ] Every new domain table has a row-level security policy")
    w("- [ ] `tools/memory.py check` passes and the dump is committed")
    w("- [ ] A `JOURNAL.md` entry is appended")
    w("")
    w("### Verification requirement")
    w("")
    w("This project's characteristic failure is a plausible but wrong belief about")
    w("LabKey Community Edition. Five capabilities look present and enforce nothing")
    w("(see `docs/gap-analysis.md`). Any statement about LabKey behaviour must be")
    w("backed by source under `/root/scicore` or by a real HTTP call, and recorded")
    w("with `tools/memory.py add verification`.")
    w("")

    w("## Requirement to Task Mapping")
    w("")
    w("| Requirement | Kind | Iteration | Title | Task |")
    w("| --- | --- | --- | --- | --- |")
    rev: dict[str, list[str]] = defaultdict(list)
    for pr, rl in trace.items():
        for rq in rl:
            rev[rq].append(pr)
    for rid in sorted(reqs):
        r = reqs[rid]
        prs = ", ".join(sorted(rev.get(rid, []))) or "—"
        w(f"| {rid} | {r['kind']} | {r['iteration'] or '—'} | {r['title']} | {prs} |")
    w("")

    w("## Task Estimation")
    w("")
    counts = defaultdict(int)
    for r in backlog:
        counts[r["size"]] += 1
    for s in ("XS", "S", "M", "L"):
        if counts[s]:
            w(f"- **{s}** ({SIZE_DAYS[s]}): {counts[s]} tasks")
    w("")
    w(f"**Total tasks**: {len(backlog)}")
    w("")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 2 if a generated file is stale instead of writing it")
    a = ap.parse_args()

    backlog, trace, reqs = load()
    if not backlog:
        print("error: the backlog is empty; nothing to render", file=sys.stderr)
        return 1

    targets = {
        REPO / "docs" / "backlog.md": render_backlog(backlog, trace),
        REPO / "specs" / "tasks" / "README.md": render_tasks_readme(backlog, trace, reqs),
    }

    stale = []
    for path, content in targets.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if a.check:
            stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO)}")

    if a.check:
        if stale:
            print("STALE generated files (run tools/render_backlog.py):")
            for p in stale:
                print(f"  - {p.relative_to(REPO)}")
            return 2
        print("generated backlog files are current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
