-- OSM project memory database - deterministic dump.
-- Source of truth in git. Regenerate the binary db with: tools/memory.py rebuild
-- Do not hand-edit; use tools/memory.py.
BEGIN TRANSACTION;
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Requirements extracted from the specification document.
CREATE TABLE IF NOT EXISTS requirements (
    id          TEXT PRIMARY KEY,            -- FR-001 / NFR-001 / CON-001
    kind        TEXT NOT NULL,               -- functional|nonfunctional|constraint|prohibition
    title       TEXT NOT NULL,
    body        TEXT NOT NULL DEFAULT '',
    source      TEXT NOT NULL,               -- e.g. "spec:§5" (traceability to the .docx)
    priority    TEXT NOT NULL DEFAULT 'must',-- must|should|could|wont
    iteration   TEXT NOT NULL DEFAULT '',    -- I0..I7 per spec §13
    status      TEXT NOT NULL DEFAULT 'open',-- open|planned|in-progress|done|deferred
    created_at  TEXT NOT NULL,
    CHECK (kind IN ('functional','nonfunctional','constraint','prohibition')),
    CHECK (priority IN ('must','should','could','wont')),
    CHECK (status IN ('open','planned','in-progress','done','deferred'))
);

-- Research findings, each pinned to verifiable evidence.
CREATE TABLE IF NOT EXISTS research (
    id            TEXT PRIMARY KEY,          -- RF-001
    topic         TEXT NOT NULL,
    finding       TEXT NOT NULL,
    evidence_kind TEXT NOT NULL,             -- source|http|doc|web|reasoning
    evidence_ref  TEXT NOT NULL DEFAULT '',  -- absolute file path, URL, or API action
    confidence    TEXT NOT NULL DEFAULT 'high', -- high|medium|low
    created_at    TEXT NOT NULL,
    CHECK (evidence_kind IN ('source','http','doc','web','reasoning')),
    CHECK (confidence IN ('high','medium','low'))
);

-- Architecture Decision Records (mirrored to specs/adr/ as markdown).
CREATE TABLE IF NOT EXISTS decisions (
    id           TEXT PRIMARY KEY,           -- ADR-001
    title        TEXT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'proposed', -- proposed|accepted|superseded|rejected
    context      TEXT NOT NULL DEFAULT '',
    decision     TEXT NOT NULL DEFAULT '',
    consequences TEXT NOT NULL DEFAULT '',
    alternatives TEXT NOT NULL DEFAULT '',
    supersedes   TEXT NOT NULL DEFAULT '',
    created_at   TEXT NOT NULL,
    CHECK (status IN ('proposed','accepted','superseded','rejected'))
);

-- Feature / gap inventory: commercial LabKey Sample Manager vs LabKey CE vs OSM.
CREATE TABLE IF NOT EXISTS features (
    id         TEXT PRIMARY KEY,             -- FEAT-001
    area       TEXT NOT NULL,                -- registry|storage|workflow|eln|search|audit|api|labkey|llm|ops|ui|security
    name       TEXT NOT NULL,
    detail     TEXT NOT NULL DEFAULT '',
    commercial TEXT NOT NULL DEFAULT 'unknown', -- yes|no|partial|unknown  (does LabKey Sample Manager have it)
    ce_support TEXT NOT NULL DEFAULT 'unknown', -- native|partial|custom|absent|unknown (LabKey CE)
    gap        TEXT NOT NULL DEFAULT 'unknown', -- none|low|medium|high  (effort for OSM)
    evidence   TEXT NOT NULL DEFAULT '',
    notes      TEXT NOT NULL DEFAULT '',
    CHECK (commercial IN ('yes','no','partial','unknown')),
    CHECK (ce_support IN ('native','partial','custom','absent','unknown')),
    CHECK (gap IN ('none','low','medium','high','unknown'))
);

-- Ordered, reviewable PR backlog.
CREATE TABLE IF NOT EXISTS backlog (
    id         TEXT PRIMARY KEY,             -- PR-001
    seq        INTEGER NOT NULL,             -- review/merge order
    title      TEXT NOT NULL,
    summary    TEXT NOT NULL DEFAULT '',
    acceptance TEXT NOT NULL DEFAULT '',     -- newline-separated acceptance criteria
    depends_on TEXT NOT NULL DEFAULT '',     -- comma-separated PR ids
    iteration  TEXT NOT NULL DEFAULT '',     -- I0..I7
    size       TEXT NOT NULL DEFAULT 'M',    -- XS|S|M|L
    branch     TEXT NOT NULL DEFAULT '',
    status     TEXT NOT NULL DEFAULT 'todo', -- todo|in-progress|review|done|blocked
    created_at TEXT NOT NULL,
    CHECK (size IN ('XS','S','M','L')),
    CHECK (status IN ('todo','in-progress','review','done','blocked'))
);

CREATE TABLE IF NOT EXISTS tasks (
    id         TEXT PRIMARY KEY,             -- T-001
    pr_id      TEXT NOT NULL REFERENCES backlog(id) ON DELETE CASCADE,
    seq        INTEGER NOT NULL DEFAULT 0,
    title      TEXT NOT NULL,
    detail     TEXT NOT NULL DEFAULT '',
    status     TEXT NOT NULL DEFAULT 'todo',
    created_at TEXT NOT NULL,
    CHECK (status IN ('todo','in-progress','done','blocked'))
);

-- How a claim about the environment was actually verified (never assume).
CREATE TABLE IF NOT EXISTS verifications (
    id          TEXT PRIMARY KEY,            -- V-001
    claim       TEXT NOT NULL,
    method      TEXT NOT NULL,               -- http|source|shell|doc
    command     TEXT NOT NULL DEFAULT '',
    result      TEXT NOT NULL,               -- pass|fail|partial
    detail      TEXT NOT NULL DEFAULT '',
    verified_at TEXT NOT NULL,
    CHECK (method IN ('http','source','shell','doc')),
    CHECK (result IN ('pass','fail','partial'))
);

-- Traceability graph: requirement -> artifact (feature, backlog item, adr, file...).
CREATE TABLE IF NOT EXISTS traceability (
    req_id        TEXT NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
    artifact_kind TEXT NOT NULL,             -- feature|backlog|decision|verification|file|spec
    artifact_ref  TEXT NOT NULL,
    PRIMARY KEY (req_id, artifact_kind, artifact_ref)
);

CREATE INDEX IF NOT EXISTS idx_backlog_seq      ON backlog(seq);
CREATE INDEX IF NOT EXISTS idx_tasks_pr         ON tasks(pr_id, seq);
CREATE INDEX IF NOT EXISTS idx_features_area    ON features(area);
CREATE INDEX IF NOT EXISTS idx_req_iteration    ON requirements(iteration);
CREATE INDEX IF NOT EXISTS idx_trace_artifact   ON traceability(artifact_kind, artifact_ref);
-- meta: 3 rows
INSERT INTO meta(key,value) VALUES('created_at','2026-08-26T08:29:24Z');
INSERT INTO meta(key,value) VALUES('project','open-sample-manager');
INSERT INTO meta(key,value) VALUES('schema_version','1');
-- requirements: 97 rows
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('CON-001','constraint','Licensing: Apache-2.0 for code, CC-BY-4.0 for content','Apache-2.0 / CC-BY-4.0.','spec:§1','must','','open','2026-08-26T08:31:35Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('CON-002','constraint','OSM must not be a LabKey UI clone','Kein LabKey-UI-Klon. OSM has its own UX (§12) and is independent of LabKey products.','spec:§1','must','','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('CON-003','constraint','LabKey is strictly downstream','LabKey ist Downstream. OSM is the system of record; LabKey CE is a publish target only.','spec:§1,§16','must','','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('CON-004','constraint','Signed notebooks are immutable','Signed unveraenderlich. No update path may mutate a signed notebook.','spec:§7','must','','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('CON-005','constraint','The UI is a client of the same API the MCP server exposes','MCP a UI: no privileged back door for the UI; both go through the same API and authorisation.','spec:§8,§10','must','','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('CON-006','constraint','Auditor role is read-only','Auditor nur lesen: the auditor can read the trail and nothing else.','spec:§9,§11','must','','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('CON-007','constraint','DPIA required before any USB identifier is processed','DPIA vor USB-Identifikatoren.','spec:§15','must','','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('CON-008','constraint','LabKey server audit supplements but never replaces the OSM trail','audit (Server) zusaetzlicher Trail - nicht OSM ersetzen.','spec:§16.1','must','','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('CON-009','constraint','Study publish requires Subject and Timepoint, otherwise reject','P-LK-STUDY: Subject+Visit, sonst reject.','spec:§17.3','must','','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('CON-010','constraint','At most one unsafe write chain per turn','Maximal eine unsichere Schreibkette pro Turn.','spec:§18.3','must','','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('CON-011','constraint','RAG corpus limited to SOPs, templates and schemas','RAG nur auf SOPs, Templates, Schemata; nicht auf PHI-ELN oder USB-Dateien.','spec:§18.3','must','','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('CON-012','constraint','Prompt injection in an SOP PDF must not unlock extra tools','Injection in SOP-PDF darf keine Extra-Tools freischalten. The tool allowlist is bound to the session, never to document content.','spec:§18.3','must','','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('CON-013','constraint','Iteration acceptance gates','I0 Auth/Audit/OpenAPI done when the hash chain verifies; I1 Registry done at aliquot; I2 Freezer map done per §5; I3 Workflow done at queue; I4 ELN done at signature; I5 Search done with RLS; I6 MCP+LabKey bridge done when the UI runs through MCP semantics; I7 Operations done at the runbook.','spec:§13','must','','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('CON-014','constraint','Freezer map, job queue, ELN and finder have independent acceptance','Freezer-Map, Job-Queue, ELN und Finder haben eigene Abnahmen.','spec:§19','must','','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-001','functional','Register, store, process, document and search samples','OSM registriert, lagert, bearbeitet, dokumentiert und sucht Proben. It is the System of Record for the sample lifecycle.','spec:§1','must','I1','open','2026-08-26T08:31:35Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-002','functional','Chain of custody for every sample','Every custody transfer (intake, move, ship, discard) is recorded and attributable to an actor.','spec:§1','must','I0','open','2026-08-26T08:31:35Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-003','functional','Freezer map with 1:1 physical correspondence','The storage model mirrors the physical freezer layout exactly (Freezer-Map 1:1); one slot holds at most one sample.','spec:§1,§5','must','I2','open','2026-08-26T08:31:35Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-004','functional','SOP-driven jobs with a work queue','SOP-Jobs mit Queue: templates instantiate jobs whose tasks appear in per-user and per-project queues.','spec:§1,§6','must','I3','open','2026-08-26T08:31:35Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-005','functional','Electronic lab notebook with signature','ELN mit Signatur: notebooks progress draft->review->approved->signed->locked.','spec:§1,§7','must','I4','open','2026-08-26T08:31:35Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-006','functional','Faceted search across samples, lineage, storage and assays','Facettierte Suche (Finder).','spec:§1,§8','must','I5','open','2026-08-26T08:31:35Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-007','functional','Hash-chained audit trail','Hash-Audit: append-only audit with SHA-256 chaining.','spec:§1,§9','must','I0','open','2026-08-26T08:31:35Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-008','functional','REST API plus MCP server','REST plus MCP. MCP tools mirror REST semantics exactly.','spec:§1,§10','must','I6','open','2026-08-26T08:31:35Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-009','functional','Publish to LabKey CE without addWebPart','LabKey-Publish ohne addWebPart. Portals are delivered as folder.xml zip archives instead.','spec:§1,§16','must','I6','open','2026-08-26T08:31:35Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-010','functional','Service decomposition into eleven domain services','identity, registry, storage, workflow, eln, search, audit, file, labkey-bridge, mcp-server, notify.','spec:§2','must','I0','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-011','functional','Every write is audited in the same transaction','Jede Schreiboperation auditiert in derselben Transaktion. Audit write and domain write share one DB transaction; no post-hoc auditing.','spec:§2','must','I0','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-012','functional','PostgreSQL with row-level security','PostgreSQL mit RLS as the persistence layer; object store for files.','spec:§2','must','I5','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-013','functional','OIDC authentication, roles and API keys','identity-service provides OIDC login, role assignment and API keys for machine clients.','spec:§2','must','I0','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-014','functional','Core entities: Project, SampleType, Source, Sample','Project(project_id: name, retention); SampleType(sample_type_id: pattern, fields, statuses); Source(source_id: human_id, meta); Sample(sample_id: status, barcode, slot).','spec:§3','must','I1','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-015','functional','AliquotLink models aliquot and derived relations','AliquotLink(parent+child) with kind in {aliquot, derived}.','spec:§3','must','I1','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-016','functional','StorageNode and Slot entities with geometry and occupancy','StorageNode/Slot carry geometry and occupied_by.','spec:§3','must','I2','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-017','functional','Job and Task entities','Job/Task with owner, due date and status.','spec:§3','must','I3','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-018','functional','Notebook entity with status and content hash','Notebook(notebook_id: status, hash).','spec:§3','must','I4','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-019','functional','AssayRun entity linking a design to samples','AssayRun(run_id: design, samples).','spec:§3','should','I1','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-020','functional','AuditEvent stores before/after state and previous hash','AuditEvent(event_id: before, after, prev_hash).','spec:§3','must','I0','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-021','functional','PublishOutbox entity for LabKey delivery','PublishOutbox(outbox_id: target, state); the transactional outbox pattern decouples OSM writes from LabKey publishing.','spec:§3,§16.2','must','I6','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-022','functional','Eight sample lifecycle statuses','Registered -> Available -> Reserved -> In Process -> Consumed | Locked | Discarded | Shipped.','spec:§3','must','I1','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-023','functional','Sample type designer','Users define sample types: naming pattern, custom fields, permitted statuses.','spec:§4','must','I1','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-024','functional','CSV bulk intake of samples','CSV import path for registering samples in bulk.','spec:§4','must','I1','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-025','functional','Create aliquots and derivatives','Aliquot (same type, split amount) and Derivat (new type, parent link) operations.','spec:§4','must','I1','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-026','functional','Sample timeline view','Chronological timeline of every event affecting a sample.','spec:§4','must','I1','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-027','functional','Picklists','Named, ordered working sets of samples that can start a job.','spec:§4,§17.2','must','I5','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-028','functional','Five-level storage hierarchy','site/building/room (list) -> device (status, zone) -> rack/drawer (grid, capacity) -> box/plate (rows x cols, A1 origin) -> slot (cell, one sample).','spec:§5','must','I2','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-029','functional','Atomic check-in, check-out and move','Check-in/out/Move atomar. A move either fully succeeds or leaves both slots unchanged.','spec:§5','must','I2','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-030','functional','Box move as an atomic batch','Box-Move als Batch: relocating a box moves all contained samples in one transaction.','spec:§5','must','I2','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-031','functional','TTL-based slot reservation','TTL-Reservierung: a slot can be reserved for a bounded time and is released automatically on expiry.','spec:§5','must','I2','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-032','functional','Slot conflict returns HTTP 409','Slot-Konflikt 409. Occupancy is enforced by a database constraint, not by application checks alone.','spec:§5','must','I2','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-033','functional','Job templates are defined without samples','Templates ohne Proben: a template is a reusable SOP skeleton; samples are bound at job start.','spec:§6','must','I3','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-034','functional','Queue views: my tasks, active jobs, board','Queue: meine Tasks, Active Jobs, Board.','spec:§6','must','I3','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-035','functional','Due-date escalation at T-1 and T+1','Eskalation T-1/T+1: notify before and after the due date.','spec:§6','must','I3','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-036','functional','Optimistic locking on task completion','Optimistic Lock auf complete: concurrent completion of the same task is rejected.','spec:§6','must','I3','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-037','functional','ELN state machine draft->review->approved->signed->locked','Only forward transitions; signed entries are immutable.','spec:§7','must','I4','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-038','functional','Signature requires re-authentication and a JSON hash','Signatur mit Re-Auth und JSON-Hash: the canonical JSON of the notebook is hashed and bound to the signer.','spec:§7','must','I4','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-039','functional','Search facets over type, lineage, storage and assay thresholds','Facetten, Lineage, Lager, Assay-Schwellen.','spec:§8','must','I5','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-040','functional','Append-only audit with SHA-256 hash chain','Each event stores prev_hash; tampering breaks the chain.','spec:§9','must','I0','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-041','functional','Daily audit checkpoint','Tages-Checkpoint anchors the chain so verification does not need a full replay.','spec:§9','must','I0','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-042','functional','Audit trail export','Trail-Export for an entity or a time range.','spec:§9','must','I0','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-043','functional','Core REST endpoints','POST /samples (intake), POST /storage/moves, POST /jobs, POST /notebooks/{id}/sign, GET /search.','spec:§10','must','I0','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-044','functional','MCP tool namespaces mirror REST semantics','osm.samples.*, osm.storage.*, osm.jobs.*, osm.eln.append_ref (draft only), osm.audit.for_entity, osm.labkey.publish_status.','spec:§10','must','I6','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-045','functional','Destructive actions require confirm=true and osm.admin.write','confirm=true plus osm.admin.write fuer destruktive Aktionen.','spec:§10','must','I6','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-046','functional','Audit records actor_type=mcp for agent-initiated writes','actor_type=mcp im Audit distinguishes agent actions from human actions.','spec:§10','must','I6','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-047','functional','Seven-role authorisation model','Reader (read); Technician (create, store, own tasks); Scientist (jobs, ELN draft, assays); Reviewer (sign); Storage/Workflow admin (structure); Project admin (types, members); Auditor (trail only).','spec:§11','must','I0','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-048','functional','Own UX with eight top-level areas','Dashboard, Samples, Sources, Map, Workflow, ELN, Finder, Admin.','spec:§12','must','I1','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-049','functional','Temperature logger integration (open)','Temperatur-Logger. Unresolved in the spec; treat as a deferred integration.','spec:§15','could','I7','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-050','functional','ZPL label printer support (open)','ZPL-Drucker. Unresolved in the spec.','spec:§15','could','I2','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-051','functional','Publish to LabKey using CSRF, createContainer, Domain, query-import, wiki-save, WebDAV','APIs wie UCI/Biomed. Reuse the established script conventions.','spec:§16','must','I6','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-052','functional','Map OSM objects onto LabKey modules','Sample/Aliquot/Lineage -> experiment Sample Types; Source -> Data Classes; AssayRun -> assay; catalogs -> list; file pointers -> pipeline/filecontent via WebDAV; SOPs -> wiki; charts -> visualization.','spec:§16.1','must','I6','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-053','functional','Publish mapping rules','Project -> LabKey project/subfolder; human_id unique plus AutoIncrement key; lineage as lookups; storage_path as a plain string (the map stays in OSM); jobs as a list read-model; ELN PDF to @files/eln/.','spec:§16.2','must','I6','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-054','functional','osm_id carried into LabKey for idempotent publishing','osm_id fuer Idempotenz: re-publishing the same object must not duplicate rows.','spec:§16.2','must','I6','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-055','functional','Outbox worker consumes sample.committed, assay.uploaded, notebook.signed','labkey-bridge (I6) arbeitet osm_publish_queue ab. Failures are stored as FAILED including the HTTP response body.','spec:§16.2','must','I6','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-056','functional','Uniform pipeline shape','Trigger -> Validierung -> Aktion -> Audit -> optional Notify/Publish/LLM. Every pipeline follows this shape.','spec:§17','must','I1','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-057','functional','Inventory pipelines P-INTAKE, P-ALIQUOT, P-DERIVE','P-INTAKE (type, id, source, slot, label); P-ALIQUOT (amount, children, lineage); P-DERIVE (type change plus parent).','spec:§17.1','must','I1','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-058','functional','Storage pipelines P-CHECKIN, P-CHECKOUT, P-BOXMOVE, P-DISCARD, P-SHIP','P-CHECKIN (occupy); P-CHECKOUT (free, Reserved); P-BOXMOVE (atomic batch); P-DISCARD (status, free slot); P-SHIP (custody, Shipped).','spec:§17.1','must','I2','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-059','functional','Work pipelines P-JOB-START, P-JOB-TASK, P-JOB-BLOCK','P-JOB-START (template+samples -> tasks, queue, notify); P-JOB-TASK (checklist, next step); P-JOB-BLOCK (escalation).','spec:§17.2','must','I3','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-060','functional','Documentation pipelines P-ASSAY-UP, P-ELN-DRAFT, P-ELN-REVIEW, P-ELN-SIGN, P-PICKLIST','P-ASSAY-UP (parse, match, index); P-ELN-SIGN (re-auth, hash, lock, PDF).','spec:§17.2','must','I4','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-061','functional','LabKey publish pipelines P-LK-SAMPLE, P-LK-ASSAY, P-LK-LIST, P-LK-STUDY','Driven by the outbox.','spec:§17.3','must','I6','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-062','functional','External data pipelines P-GEO-META, P-UNIPROT, P-BAG-SYNC, P-SPHN-TOKEN','P-GEO-META (accession metadata, no FASTQ); P-UNIPROT (accessions -> meta fields); P-BAG-SYNC (cron Wednesday, IDD-CSV); P-SPHN-TOKEN (manual, concept map only).','spec:§17.3','should','I7','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-063','functional','Operations pipelines','P-REINDEX, P-AUDIT-CKPT, P-RETENTION, P-KEY-ROTATE, P-RESTORE-DRILL.','spec:§17.4','must','I7','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-064','functional','LLMs act only through MCP tools','LLMs nutzen nur MCP-Tools. Keine Domain-Aktion ohne Tool.','spec:§18','must','I6','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-065','functional','Every LLM call emits an llm.invoke audit event','llm.invoke records model_id and request_id.','spec:§18','must','I6','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-066','functional','Assistant use cases','CSV intake mapping, SOP->template drafting, natural-language finder, free-slot lookup, queue prioritisation (read-only), ELN drafting, assay mismatch explanation, audit questions, LabKey error triage, GEO/PRIDE metadata.','spec:§18.1','should','I6','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('FR-067','functional','Three assistant channels','UI chat against the local MCP; external assistants via API key on POST /mcp; batch workers on a service account writing into a review queue.','spec:§18.3','must','I6','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('NFR-001','nonfunctional','Freezer map renders 1000 boxes of 81 slots smoothly','1000 Boxen a 81 Slots ohne Ruckeln (~81000 slots).','spec:§5','must','I2','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('NFR-002','nonfunctional','Search P95 below 300 ms at one million samples','P95 < 300 ms bei 1e6 Proben.','spec:§8','must','I5','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('NFR-003','nonfunctional','API P95 latency below 200 ms','API P95 < 200 ms.','spec:§14','must','I0','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('NFR-004','nonfunctional','100 concurrent users','100 parallele Nutzer.','spec:§14','must','I0','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('NFR-005','nonfunctional','One million samples','1e6 Proben.','spec:§14','must','I0','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('NFR-006','nonfunctional','Point-in-time recovery for seven days','PITR 7 Tage.','spec:§14','must','I7','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('NFR-007','nonfunctional','Target WCAG 2.2 AA accessibility','WCAG 2.2 AA anstreben.','spec:§14','should','I1','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('PRO-001','prohibition','No SPHN/USB patient payload in OSM','Kein SPHN-/USB-Patientenpayload. Only tokenised identifiers may enter OSM.','spec:§1','must','','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('PRO-002','prohibition','Study PID only as an opaque token','Study-PID nur als Token. No re-identifiable patient identifier is stored.','spec:§4','must','','open','2026-08-26T08:31:36Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('PRO-003','prohibition','Strip PHI on publish','PHI beim Publish streichen.','spec:§16.2','must','','open','2026-08-26T08:31:37Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('PRO-004','prohibition','Do not use addWebPart against LabKey','Kein addWebPart. Portals are delivered as folder.xml zip archives.','spec:§16','must','','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('PRO-005','prohibition','LLMs may never discard, ship or lock without a human','Discard/Ship/Lock ohne Mensch verboten.','spec:§18.2','must','','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('PRO-006','prohibition','LLMs may never sign an ELN entry','ELN-Signatur verboten.','spec:§18.2','must','','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('PRO-007','prohibition','LLMs may never change permissions','Rechte aendern verboten.','spec:§18.2','must','','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('PRO-008','prohibition','No PHI in prompts','PHI in Prompts verboten.','spec:§18.2','must','','open','2026-08-26T08:31:38Z');
INSERT INTO requirements(id,kind,title,body,source,priority,iteration,status,created_at) VALUES('PRO-009','prohibition','No SQL or shell access outside the declared tools','SQL/Shell ausserhalb der Tools verboten.','spec:§18.2','must','','open','2026-08-26T08:31:38Z');
-- research: 15 rows
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-001','LabKey CE premium boundary','CE ships the service interfaces for its premium capabilities with no implementation registered, and each degrades to a silent no-op rather than failing. InventoryService.get() returns null; SampleStatusService.isOperationPermitted() always returns true; ComplianceService passes PHI through; McpService is a Noop. Code that probes for these features will appear to work while enforcing nothing.','source','/root/scicore/server/modules/platform/api/src/org/labkey/api/{inventory,qc,compliance,mcp}/','high','2026-08-26T08:41:57Z');
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-002','Sample status enforcement in CE','Because no SampleStatusService provider is registered, DefaultSampleStatusService.isOperationPermitted() returns true unconditionally. LabKey CE therefore enforces no sample status rules at all: a sample marked Consumed can still be edited, aliquoted or derived. Status semantics must be owned by OSM.','source','/root/scicore/server/modules/platform/api/src/org/labkey/api/qc/SampleStatusService.java:84','high','2026-08-26T08:41:57Z');
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-003','Aliquot amounts are floats in LabKey','exp.Material stores StoredAmount as DOUBLE PRECISION and AliquotVolume as FLOAT. Repeated aliquot splitting accumulates floating-point error. OSM uses NUMERIC and Decimal end to end (ADR-0002) and accepts precision loss only at the publish boundary.','source','/root/scicore/server/modules/platform/experiment/resources/schemas/dbscripts/postgresql/exp-0.000-25.000.sql:323-368','high','2026-08-26T08:41:57Z');
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-004','Barcode field type is reachable in CE via the API','The Unique ID field type is blocked only in the bundled field-editor JavaScript, which checks isCommunityDistribution(). The server applies no gate, so creating a domain property with conceptURI http://www.labkey.org/types#storageUniqueId through property-createDomain.api yields DbSequence-backed auto-generated barcode values in CE. This makes barcode publishing to LabKey feasible without premium.','source','/root/scicore/build/deploy/modules/core/web/gen/domainDesigner.*.js and .../api/data/ColumnRenderPropertiesImpl.java:48','high','2026-08-26T08:41:57Z');
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-005','LabKey CE search cannot satisfy OSM spec 8','CE search is Lucene 10.5 with category filtering only. There is no faceting, no aggregation and no result counts per category, and sample categories are excluded from advanced search by default. OSM spec 8 requires facets over type, lineage, storage and assay thresholds at P95 below 300 ms across a million samples, so the finder must be built in OSM against PostgreSQL.','source','/root/scicore/server/modules/platform/search/src/org/labkey/search/model/LuceneSearchServiceImpl.java:1756-1766','high','2026-08-26T08:41:57Z');
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-006','LabKey CE authentication cannot satisfy OSM spec 2','CE ships only database-password and API-key authentication. There is no OIDC, SAML, CAS or LDAP authentication provider; OpenLdapSync only synchronises users and groups. OSM spec 2 requires OIDC, which OSM must therefore provide itself.','source','enumeration of AuthenticationProvider implementations under /root/scicore/server/modules','high','2026-08-26T08:41:57Z');
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-007','LabKey CE has no row-level security framework','Security is container plus role. ExpMaterialTableImpl.hasPermission delegates entirely to Container.hasPermission, and neither ExpMaterial nor ExpSampleType implements SecurableResource, so samples cannot carry ACLs. Restricting who sees which samples requires container partitioning. OSM spec 2 requires RLS, which PostgreSQL provides natively and OSM will use directly.','source','/root/scicore/server/modules/platform/experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java:1844-1860','high','2026-08-26T08:41:57Z');
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-008','API key restriction roles are the right credential for the bridge','LabKey CE can mint an API key bound to a reduced role, limited to ReaderRole, AuthorRole, EditorWithoutDeleteRole or EditorRole. The labkey-bridge should authenticate with an EditorWithoutDelete-restricted key so a compromised bridge credential cannot delete published data. API keys must first be enabled in site settings, since allowApiKeys defaults to false.','source','/root/scicore/server/modules/platform/core/src/org/labkey/core/security/SecurityController.java:2305-2310','high','2026-08-26T08:41:57Z');
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-009','Correct LabKey action names','The bulk import action is query-import.api, not query-importData.api. There is no experiment-saveMaterials.api. experiment-deriveSamples is a FormViewAction serving a .view, while the programmatic endpoint is experiment-derive.api. Domain actions live under the property- controller which is implemented in the experiment module. Action naming follows @ActionNames when present, else the class name minus the Action suffix with only the first character lowercased.','source','/root/scicore/server/modules/platform/query/src/org/labkey/query/controllers/QueryController.java:4147 and SpringActionController.java:1084-1172','high','2026-08-26T08:41:57Z');
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-010','LabKey CE audit is detailed but not tamper-evident','Sample tables default to DETAILED audit behaviour and SampleTimelineEvent stores oldRecordMap and newRecordMap with a TransactionID, unconditionally and with no edition gate. But there is no hash chaining and no checkpoint, so alteration by anyone with database access is undetectable. OSM spec 9 requires detection, which is why the OSM trail is primary and the LabKey trail is a supplement (spec 16.1).','source','/root/scicore/server/modules/platform/experiment/src/org/labkey/experiment/samples/SampleTimelineAuditProvider.java and ExpMaterialTableImpl.java:2019','high','2026-08-26T08:41:57Z');
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-011','The laboratory module is prior art for a freezer model','The deployed LabDevKit laboratory module has laboratory.freezers and laboratory.samples with freezer, cane, box, box_row and box_column columns, plus freezer_space_summary and freezer_usage_by_box reporting queries. It is worth reading for layout ideas, but it is a separate schema from exp.material, has no slot-level exclusion constraint, no reservation TTL and no atomic move, so it cannot satisfy OSM spec 5.','source','/root/scicore/server/modules/LabDevKitModules/laboratory/resources/schemas/dbscripts/postgresql/laboratory-12.24-12.25.sql:40','high','2026-08-26T08:41:57Z');
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-012','File-based LabKey module layout','ModuleLoader reads <moduleDir>/config/module.properties and instantiates SimpleModule when ModuleClass is absent. Resources are queries/<schema>/<Query>.sql, views/<name>.html with .view.xml and .webpart.xml siblings, web/<module>/, and schemas/. Note that the deployed scicoreBrand module places module.properties at its root rather than under config/, so ModuleLoader ignores it - prior art not to copy.','source','/root/scicore/server/modules/platform/api/src/org/labkey/api/module/ModuleLoader.java:1126-1238','high','2026-08-26T08:41:57Z');
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-013','MCP framework present in CE but inert','CE contains the MCP framework (McpService, McpContext, AbstractAgentAction) and tool definitions in CoreMcp, QueryMcp and SearchMcp, but no McpService implementation is registered and SearchModule has its registration commented out as not ready. There is no working MCP server in this build, so OSM spec 18 must be served by OSM''s own MCP server.','source','/root/scicore/server/modules/platform/api/src/org/labkey/api/mcp/ and SearchModule.java:136-141','high','2026-08-26T08:41:58Z');
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-014','LabKey session and TLS conventions established by the user''s scripts','The user''s install scripts bootstrap a session by probing login-whoAmI.api with a cookie jar and scraping the CSRF field, falling back to login-loginApi.api with email and password. They deliberately avoid curl -f so 4xx bodies stay readable, avoid -L and set --max-redirs 0 because importFolder.post redirects to a host whose certificate does not match, and auto-enable -k for loopback HTTPS. Credentials come from LK_URL, LK_USER, LK_PASSWORD, LK_APIKEY, LK_CONTEXT and LK_INSECURE with matching flags and no prompting.','source','/root/install-labkey-uci-datasets.sh, /root/install-labkey-v940-evidence.sh','high','2026-08-26T08:41:58Z');
INSERT INTO research(id,topic,finding,evidence_kind,evidence_ref,confidence,created_at) VALUES('RF-015','addWebPart misbehaves on LabKey CE 26','The user''s scripts document that project-addWebPart.api is a FormViewAction whose getSuccessURL() calls addReturnUrl(), so omitting returnUrl throws a NullPointerException and floods labkey.log even when the web part was saved. OSM spec 16 independently forbids addWebPart and requires portals to be delivered as folder.xml archives, which avoids the problem entirely.','source','/root/install-labkey-uci-datasets.sh','high','2026-08-26T08:41:58Z');
-- decisions: 8 rows
INSERT INTO decisions(id,title,status,context,decision,consequences,alternatives,supersedes,created_at) VALUES('ADR-0001','OSM Is The System Of Record And LabKey CE Is A Downstream Publish Target','accepted','The brief framed the work as a Sample Manager for LabKey CE; the specification says OSM is independent of LabKey products, is not a LabKey UI clone, and that LabKey is downstream. LabKey CE has no storage, workflow or ELN substrate to extend.','Build OSM standalone with its own PostgreSQL database, services, API and UI. A labkey-bridge publishes downstream.','Positive: OSM owns RLS, the eight-status lifecycle, slot constraints, the audit chain and its own performance targets. Negative: sample types, lineage and aliquots are reimplemented despite existing in exp; two systems to operate; publish must be idempotent.','Build as a LabKey module (contradicts the spec, no RLS, audit not immutable); hybrid with samples in exp.material (makes same-transaction auditing impossible).','','2026-08-26T08:42:47Z');
INSERT INTO decisions(id,title,status,context,decision,consequences,alternatives,supersedes,created_at) VALUES('ADR-0002','Python, FastAPI And PostgreSQL As The Implementation Stack','accepted','The spec fixes PostgreSQL with RLS and requires OpenAPI and an MCP server. The host already provides PostgreSQL 18.6 and Python 3.11.','Python with FastAPI, SQLAlchemy 2.x and Alembic; React with TypeScript for the UI as a separate API client.','Positive: OpenAPI and boundary validation come from the type model; Decimal avoids float drift in aliquot arithmetic; the connection stays visible for RLS. Negative: async transaction scoping must be enforced by a unit-of-work helper and tested, because the same-transaction audit rule fails silently otherwise.','Java with Spring Boot (heaviest toolchain, weaker MCP SDK); TypeScript with NestJS (ORM fights RLS, float semantics hazardous for amounts).','','2026-08-26T08:42:47Z');
INSERT INTO decisions(id,title,status,context,decision,consequences,alternatives,supersedes,created_at) VALUES('ADR-0003','Tamper-Evident Audit Written Inside The Domain Transaction','accepted','Spec 2 requires every write audited in the same transaction and spec 9 requires an append-only SHA-256 chain with a daily checkpoint. A naive chain forks under concurrency.','Database triggers guarantee completeness, the unit-of-work additionally emits semantic domain events, and a PostgreSQL advisory lock serialises hash and sequence assignment so the chain is linear.','Positive: no write escapes the trail including a direct psql session; tampering is detectable; the auditor role is read-only by grant rather than by convention. Negative: the advisory lock serialises hash assignment and must be load-tested against the 100-concurrent-user target.','Application-level helper only (completeness depends on discipline); triggers only (cannot express business events like notebook.signed at the altitude the export needs).','','2026-08-26T08:42:47Z');
INSERT INTO decisions(id,title,status,context,decision,consequences,alternatives,supersedes,created_at) VALUES('ADR-0004','Slot Occupancy Enforced By A Database Constraint','accepted','Spec 5 requires one sample per slot, atomic moves, TTL reservations and HTTP 409 on conflict. Check-then-write races, and a race here breaks the freezer map''s 1:1 correspondence with physical reality.','Model occupancy and reservation as one slot_assignment row with a tstzrange, enforced by EXCLUDE USING gist (slot_id WITH =, valid_during WITH &&) via btree_gist.','Positive: double occupancy is impossible; TTL expiry is a property of the data rather than a sweeper job that can crash silently; slot history is a byproduct feeding the sample timeline and audit export. Negative: btree_gist must be installed by a migration that fails loudly; GiST cost must be measured against the 81000-slot target.','Application-level check-then-write (races, disqualifying); partial unique index on occupancy (does not cover reservations, so the invariant lives in two places).','','2026-08-26T08:42:47Z');
INSERT INTO decisions(id,title,status,context,decision,consequences,alternatives,supersedes,created_at) VALUES('ADR-0005','Transactional Outbox For LabKey Publishing','accepted','Spec 3 defines PublishOutbox and spec 16.2 requires the bridge to drain a queue, store failures with the HTTP body, and use osm_id for idempotency. LabKey can be down or slow.','The domain transaction inserts an osm_publish_queue row alongside the domain write; a worker drains it with SELECT FOR UPDATE SKIP LOCKED and upserts on osm_id.','Positive: a publish can never be lost because intent and write share a commit; LabKey downtime only grows the queue; publish lag is one observable metric. Negative: eventual consistency, so the UI must show publish state explicitly rather than implying LabKey already has the sample.','Synchronous publish in the transaction (LabKey downtime becomes OSM downtime); post-commit async job (a crash between commit and enqueue loses the publish silently).','','2026-08-26T08:42:47Z');
INSERT INTO decisions(id,title,status,context,decision,consequences,alternatives,supersedes,created_at) VALUES('ADR-0006','The MCP Server Is A Thin Adapter Over The REST API','accepted','Spec 10 says MCP tools are REST semantics, spec 8 says the UI goes through the same surface, and spec 18.3 requires that prompt injection in an SOP PDF cannot unlock extra tools. A second door into the domain would drift from the first.','Each MCP tool is a thin translation onto a REST call authenticated as the agent''s principal, so there is exactly one authorisation implementation.','Positive: an agent structurally cannot exceed the role it authenticates as; the tool allowlist is bound to the session at authentication time and is not derived from document content. Negative: one loopback HTTP hop per tool call; errors need translation without leaking data the principal cannot see.','MCP with direct in-process domain access (two authorisation paths that will drift); shared service layer with two transports (sharing is enforced only by review, and agent-specific prohibitions have no natural home).','','2026-08-26T08:42:47Z');
INSERT INTO decisions(id,title,status,context,decision,consequences,alternatives,supersedes,created_at) VALUES('ADR-0007','Project Memory Is A Git-Tracked SQL Dump','accepted','The project runs across many sessions that each start without prior context. Durable knowledge must be both machine-queryable and reviewable.','Track .sdd/memory.sql as the deterministic source of truth and treat .sdd/memory.db as a derived, git-ignored artifact rebuilt on demand.','Positive: every knowledge change is a reviewable text diff; merge conflicts are ordinary text conflicts; the CLI enforces id patterns, foreign keys and enums. Negative: contributors must use the CLI, and the dump must be regenerated on every write - handled by regenerating automatically and failing tools/memory.py check when the tracked copy has drifted.','Commit the binary db (no reviewable diff, unresolvable merges, not byte-stable); markdown only (no cross-cutting queries, no constraints, traceability degrades to unvalidated links).','','2026-08-26T08:42:47Z');
INSERT INTO decisions(id,title,status,context,decision,consequences,alternatives,supersedes,created_at) VALUES('ADR-0008','Credentials Come Exclusively From The Environment','accepted','No secret may enter the repository. The user''s existing scripts already establish LK_URL, LK_USER, LK_PASSWORD, LK_APIKEY, LK_CONTEXT and LK_INSECURE, but build-labkey-community.sh also shows the failure mode to avoid: defaulting a password to a real value that works, so nobody notices.','Every credential is read from the environment with no defaults, no config files and no prompting; a missing required variable aborts with a message naming it. Credentials pass to subprocesses through the environment, never as command-line arguments.','Positive: committing a secret would require deliberately writing one into a file; CI and secret managers work unchanged; the repository has no git remote until GITHUB_TOKEN is supplied. Negative: variables must be re-exported per shell, and are visible to other processes of the same user - accepted deliberately for a single-user research server.','Git-ignored config file (one git add -f from disaster, persists on disk); a secret manager (right for production, disproportionate here, and not foreclosed since the environment is the interface it injects into).','','2026-08-26T08:42:47Z');
-- verifications: 18 rows
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-001','LabKey CE 26.7.5 exposes no inventory/storage/freezer/workflow/eln schema','http','POST /home/query-getSchemas.api {includeHidden:true}','pass','Returned: announcement, assay, auditLog, cluster, core, exp, exp.data, exp.materials, flow, issues, ListManager, lists, ms2, pipeline, plate, protein, query, samples, study, targetedms, targetedmslists, wiki. None of inventory/storage/freezer/sampleManager/workflow/eln/labbook present.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-002','exp.SampleStateType offers only three state types against the eight statuses OSM spec 3 requires','http','POST /home/query-selectRows.api {schemaName:exp, queryName:SampleStateType}','pass','rowCount 3: Available(0), Consumed(1), Locked(2). exp.SampleStatus is empty (0 rows).','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-003','The host provides PostgreSQL 18.6, Python 3.11.13, Node 24.14.0, JDK 21, sqlite 3.43.2 and git 2.53.0','shell','psql --version; python3 -V; node -v; java -version; sqlite3 --version; git --version','pass','All present. PostgreSQL 18.6 supports btree_gist, required by ADR-0004.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-004','exp.Materials carries aliquot, amount and status columns natively in CE','http','POST /home/query-getQueryDetails.api {schemaName:exp, queryName:Materials}','pass','42 columns including RootMaterialRowId, AliquotedFromLSID, IsAliquot, AliquotCount, AliquotVolume, AliquotUnit, AvailableAliquotCount, AvailableAliquotVolume, StoredAmount, Units, RawAmount, SampleState, MaterialExpDate, IsPlated, Ancestors.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-005','The auditLog schema is queryable and includes SampleTimelineEvent','http','POST /home/query-getQueries.api {schemaName:auditLog}','pass','37 queries including SampleTimelineEvent, SampleSetAuditEvent, ExperimentAuditEvent, TransactionAuditEvent, QueryUpdateAuditEvent.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-006','Login via POST /login-loginApi.api with email and password returns a CSRF token usable as the X-LABKEY-CSRF header','http','POST /login-loginApi.api email=<user> password=<from env>; then GET /login-whoami.api','pass','HTTP 200, success true, CSRF returned and matching the X-LABKEY-CSRF cookie. whoami confirms the authenticated principal. Credentials supplied via environment variables only.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-007','The deployed LabKey tree contains no premium modules','source','list /root/scicore/build/deploy/modules','pass','43 modules: platform 23, commonAssays 10, DiscvrLabKeyModules 8, LabDevKitModules 2, targetedms 1, scicoreBrand 1. No sampleManager, inventory, biologics, labbook, recipe, compliance or premium module present.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-008','InventoryService, SampleStatusService, ComplianceService and McpService are unimplemented SPI stubs in CE','source','read /root/scicore/server/modules/platform/api/src/org/labkey/api/{inventory,qc,compliance,mcp}/*.java','pass','InventoryService.get() returns null. SampleStatusService falls back to DefaultSampleStatusService: supportsSampleStatus() false, isOperationPermitted() always true. ComplianceService falls back to a pass-through. McpService.get() returns NoopMcpService with isEnabled() false.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-009','LabKey CE has no row-level security on exp.material','source','read /root/scicore/server/modules/platform/experiment/src/org/labkey/experiment/api/ExpMaterialTableImpl.java:1844-1860','pass','Every branch of hasPermission() delegates to Container.hasPermission(). No SimpleFilter on CreatedBy, no owner check, no per-row policy. Neither ExpMaterial nor ExpSampleType implements SecurableResource, so samples cannot carry ACLs.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-010','LabKey CE search has no faceting','source','grep -r facet /root/scicore/server/modules/platform/search /root/scicore/server/modules/platform/api/src/org/labkey/api/search','pass','Zero occurrences of facet; no lucene-facet dependency. Only category filtering via OR''d TermQuery on searchCategories. SearchResult returns totalHits, hits, offset with no counts or aggregations.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-011','The Unique ID barcode field type is server-supported in CE but hidden by the UI','source','read ColumnRenderPropertiesImpl.java:48-49, BaseColumnInfo.java:653-665, build/deploy/modules/core/web/gen/domainDesigner.*.js','pass','STORAGE_UNIQUE_ID_CONCEPT_URI drives a DbSequence-backed auto-generated value server-side. The bundled field editor refuses the type when isCommunityDistribution(), but there is no server-side gate: property-createDomain.api with that conceptURI still works.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-012','LabKey CE ships no OIDC, SAML, CAS or LDAP authentication provider','source','enumerate AuthenticationProvider implementations under /root/scicore/server/modules','pass','Only DbLoginAuthenticationProvider (password plus API keys), LoginAttemptDisableLoginProvider, and two devtools-only test providers. OpenLdapSync syncs users and groups but contains no AuthenticationProvider.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-013','API keys exist in CE but are disabled by default','source','read /root/scicore/server/modules/platform/api/src/org/labkey/api/settings/SiteSettingsProperties.java:125-146 and AppPropsImpl.java:546-561','pass','allowApiKeys and allowSessionKeys both default to false. core.APIKeys stores only a SHA-256 crypt. Keys are 64-char hex with no prefix. RestrictionRole allows minting a reduced-privilege key limited to Reader, Author, EditorWithoutDelete or Editor.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-014','The bulk import action is named query-import.api, not query-importData.api','source','read /root/scicore/server/modules/platform/query/src/org/labkey/query/controllers/QueryController.java:4147','pass','ImportAction extends AbstractQueryImportAction resolves to query-import.api. This is the endpoint behind LABKEY.Query.importData. The user''s own scripts confirm the same name.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-015','experiment-saveMaterials.api does not exist and experiment-deriveSamples is a view rather than an API','source','grep for SaveMaterialsAction and DeriveSamplesAction across /root/scicore/server/modules','pass','No SaveMaterialsAction class anywhere. DeriveSamplesAction extends FormViewAction, so it serves experiment-deriveSamples.view. The programmatic derivation endpoint is experiment-derive.api (DeriveAction, Insert permission).','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-016','PHI column tagging exists in CE but masks nothing','source','read /root/scicore/server/modules/platform/api/src/org/labkey/api/data/PHI.java, compliance/PhiColumnBehavior.java, FilteredTable.applyTableRules','pass','The PHI enum, PhiColumnBehavior and the FilteredTable call sites all exist, but no module registers a ComplianceService, so DefaultComplianceService passes everything through with getMaxAllowedPhi() = Restricted. PHI tags survive export and import but provide no protection.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-017','The laboratory module deployed on this server contains a freezer model separate from exp.material','source','read /root/scicore/server/modules/LabDevKitModules/laboratory/resources/schemas/dbscripts/postgresql/laboratory-12.24-12.25.sql:40 and laboratory.xml:91','pass','laboratory.freezers(rowid,name,canes,boxes,rows,columns,comments,container) and laboratory.samples(freezerid,location,freezer,cane,box,box_row,box_column,quantity,...) exist. Not integrated with Sample Types, no slot exclusion constraint, no reservation TTL, no atomic move.','2026-08-26T08:41:57Z');
INSERT INTO verifications(id,claim,method,command,result,detail,verified_at) VALUES('V-018','LabKey CE sample tables audit at DETAILED level by default, storing before and after record maps','source','read ExpMaterialTableImpl.java:2019 and SampleTimelineAuditProvider.java','pass','getAuditBehavior() returns DETAILED for sample tables. SampleTimelineEvent carries oldRecordMap and newRecordMap plus TransactionID, with canDeleteOldRows() false. No hash chaining, no checkpoint, so tampering by a database administrator is undetectable.','2026-08-26T08:41:57Z');
COMMIT;
