"""
Credential and connection configuration for the LabKey publish target.

Everything here comes from the environment. There are no defaults that are
credentials, and no configuration file is read — see
``specs/adr/0008-credentials-exclusively-from-the-environment.md`` for why,
including the specific failure mode this avoids (a default that is a real
password works, so nobody notices it was committed).

Variable names deliberately match the user's existing ``install-labkey-*.sh``
scripts so that one exported environment drives both.
"""
from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from ipaddress import ip_address
from typing import Mapping
from urllib.parse import urlsplit

DEFAULT_URL = "https://127.0.0.1:8443"

#: Hostnames that are loopback by name rather than by address.
_LOOPBACK_NAMES = frozenset({"localhost", "localhost.localdomain"})


class ConfigError(Exception):
    """Configuration is missing or contradictory. Always fatal, never guessed."""


def _is_loopback(host: str) -> bool:
    """True when *host* certainly refers to this machine.

    Used only to decide whether skipping TLS verification is defensible: the
    deployment terminates TLS with a self-signed certificate generated by
    ``build-labkey-community.sh``, so loopback HTTPS cannot verify. A non-
    loopback host must present a valid certificate or opt out explicitly.
    """
    if not host:
        return False
    host = host.strip("[]").lower()
    if host in _LOOPBACK_NAMES:
        return True
    try:
        return ip_address(host).is_loopback
    except ValueError:
        return False


@dataclass(frozen=True)
class LabKeyConfig:
    """Resolved connection settings.

    The credential fields are excluded from ``repr`` so that a config object
    appearing in a traceback, a log line or a debugger cannot disclose them.
    """

    url: str
    context: str = "auto"
    user: str | None = None
    password: str | None = field(default=None, repr=False)
    api_key: str | None = field(default=None, repr=False)
    verify_tls: bool = True
    timeout: float = 60.0

    def __post_init__(self) -> None:
        if not self.url:
            raise ConfigError("LK_URL is empty; set it or leave it unset to use the default")
        parts = urlsplit(self.url)
        if parts.scheme not in ("http", "https"):
            raise ConfigError(
                f"LK_URL must be an http or https URL, got scheme {parts.scheme!r}")
        if not parts.netloc:
            raise ConfigError(f"LK_URL has no host: {self.url!r}")

    # -- credential resolution ------------------------------------------------

    @property
    def uses_api_key(self) -> bool:
        """API keys take precedence over user/password, matching the shell scripts.

        An API key is preferred because it can be minted with a restriction role
        and revoked independently of the owning account.
        """
        return bool(self.api_key)

    def auth_headers(self) -> dict[str, str]:
        """Headers carrying the API key, or an empty mapping when using a password.

        LabKey accepts the key as an ``apikey:`` header, as a bearer token, or as
        the basic-auth username. The header form is used because it never
        appears in a URL and cannot leak through a referrer or an access log.
        """
        return {"apikey": self.api_key} if self.api_key else {}

    def describe(self) -> str:
        """A one-line summary safe to log. Names the auth mode, never the secret."""
        mode = "api-key" if self.uses_api_key else f"password (user={self.user})"
        tls = "verified" if self.verify_tls else "unverified"
        return f"{self.base_url_candidates()[0]} auth={mode} tls={tls}"

    # -- URL construction -----------------------------------------------------

    def base_url_candidates(self) -> list[str]:
        """Base URLs to probe, in order.

        LabKey may be served at the root or under a ``/labkey`` servlet context.
        Embedded CE 24.3 and later default to an empty context; WAR deployments
        use ``/labkey``. ``LK_CONTEXT=auto`` probes both rather than assuming,
        because assuming produces a 404 on every call.
        """
        origin = self.url.rstrip("/")
        if self.context.lower() == "auto":
            return [origin, f"{origin}/labkey"]
        ctx = self.context.strip("/")
        return [f"{origin}/{ctx}" if ctx else origin]


def _env_flag(raw: str | None) -> bool | None:
    """Parse a tri-state flag: unset, true-ish, or false-ish."""
    if raw is None or raw == "":
        return None
    return raw.strip().lower() in ("1", "true", "yes", "on")


def load_config(env: Mapping[str, str] | None = None) -> LabKeyConfig:
    """Build a :class:`LabKeyConfig` from the environment.

    Raises :class:`ConfigError` naming the missing variable when no usable
    credential is present. It never falls back to a guess, prompts, or reads a
    file — a script that cannot authenticate must say so immediately rather than
    failing later with an opaque 401.
    """
    env = os.environ if env is None else env

    url = (env.get("LK_URL") or DEFAULT_URL).strip()
    context = (env.get("LK_CONTEXT") or "auto").strip()
    user = (env.get("LK_USER") or "").strip() or None
    password = env.get("LK_PASSWORD") or None
    api_key = (env.get("LK_APIKEY") or "").strip() or None

    if not api_key and not (user and password):
        missing = []
        if not user:
            missing.append("LK_USER")
        if not password:
            missing.append("LK_PASSWORD")
        raise ConfigError(
            "no LabKey credential available: set LK_APIKEY, or set both "
            f"LK_USER and LK_PASSWORD (missing: {', '.join(missing)}). "
            "Credentials are read from the environment only; see memory.md."
        )

    insecure = _env_flag(env.get("LK_INSECURE"))
    host = urlsplit(url).hostname or ""
    loopback = _is_loopback(host)
    scheme = urlsplit(url).scheme
    if insecure is None:
        # Not specified: skip verification for loopback only. The deployment's
        # certificate is self-signed, so verifying loopback always fails; any
        # other host is a real network destination and must verify.
        verify = not loopback
    else:
        verify = not insecure

    if not verify and not loopback and scheme == "https":
        # Relaxing TLS towards a host that is not this machine exposes the
        # credential to anyone on the path. ADR-0008 keeps the escape hatch,
        # because internal certificate authorities are a real situation, but it
        # must never be quiet: an operator who did not mean it needs to see it.
        logging.getLogger("osm.labkey").warning(
            "TLS verification is DISABLED for the non-loopback host %r. "
            "Credentials will be sent over a connection whose certificate is "
            "not checked. Unset LK_INSECURE unless this is deliberate.", host)

    timeout_raw = env.get("LK_TIMEOUT")
    try:
        timeout = float(timeout_raw) if timeout_raw else 60.0
    except ValueError as exc:
        raise ConfigError(f"LK_TIMEOUT must be a number, got {timeout_raw!r}") from exc
    if timeout <= 0:
        raise ConfigError(f"LK_TIMEOUT must be positive, got {timeout}")

    return LabKeyConfig(
        url=url,
        context=context,
        user=user,
        password=password,
        api_key=api_key,
        verify_tls=verify,
        timeout=timeout,
    )
